#!/bin/bash

#POSSIBLE OPTIONS
#--debug
#--no-debug
#--clean

DEFAULT_DEBUG="-DDEBUG=OFF"

if [ $# -gt 0 ];
	then
		if [[ $* == *"--clean"* ]];
			then
				if [ -d "exec" ]
					then
						echo "got to delete exec"
						rm -rf exec
					mkdir exec
				elif [ ! -d "exec" ];
					then
						mkdir exec
				fi
		fi
		if [[ $* = *"--debug"* ]];
			then
				DEFAULT_DEBUG="-DDEBUG=ON"
		elif [[ $* = *"--no-debug"* ]];
			then
				DEFAULT_DEBUG="-DDEBUG=OFF"
		fi
		cd exec
		cmake $DEFAULT_DEBUG ..
		make
else
	cd exec
	cmake $DEFAULT_DEBUG ..
	make
fi