#!/bin/bash

#POSSIBLE OPTIONS
#--debug
#--clean
#--code-check
#--mem-check
#--test-daemon
#--test-utils
#--test-memory

DEBUG="-DDEBUG=OFF"
CODE_CHECK="-DCODE_CHECK=OFF"
TEST_DAEMON="-DTEST_DAEMON=OFF"
TEST_UTILS="-DTEST_UTILS=OFF"
TEST_MEMORY="-DTEST_MEMORY=OFF"

if [ ! -d "exec" ];
	then
		mkdir exec
fi

if [ $# -gt 0 ];
	then
		if [[ $* == *"--clean"* ]];
			then
				rm -rf exec
				mkdir exec
		fi

		if [[ $* = *"--debug"* ]];
			then
				DEBUG="-DDEBUG=ON"
		fi

		if [[ $* = *"--code-check"* ]];
			then
				CODE_CHECK="-DCODE_CHECK=ON"
		fi
		
		if [[ $* = *"--test-daemon"* ]];
			then
				TEST_DAEMON="-DTEST_DAEMON=ON"
		fi
		
		if [[ $* = *"--test-utils"* ]];
			then
				TEST_UTILS="-DTEST_UTILS=ON"
		fi

		if [[ $* = *"--test-memory"* ]];
			then
				TEST_MEMORY="-DTEST_MEMORY=ON"
		fi

		cd exec
		cmake $DEBUG $CODE_CHECK $TEST_DAEMON $TEST_UTILS $TEST_MEMORY ..
		make

		if [[ $* == *"--mem-check=file"* ]];
			then
				valgrind --leak-check=full --trace-children=yes --track-origins=yes --show-leak-kinds=all -s --log-file=ValgrindOutput.txt ./SupervisorDaemon
				echo -e "-- \033[0;31mValgrind\033[0m results written in \033[0;32mexec/ValgrindOutput.txt\033[0m file!"
		elif [[ $* == *"--mem-check=console"* ]] || [[ $* == *"--mem-check"* ]];
			then
				echo -e "-- \033[0;31mValgrind\033[0m results showing in the \033[0;32mconsole\033[0m!"
				valgrind --leak-check=full --trace-children=yes --track-origins=yes --show-leak-kinds=all -s ./SupervisorDaemon
		fi
		cd ..
		#if [ $TEST == "-DTEST=ON" ]
		#	then
		#		./exec/test/SupervisorDaemon-test
		#fi
else
	cd exec
	cmake $DEBUG $CODE_CHECK $TEST_DAEMON $TEST_UTILS $TEST_MEMORY..
	make
	cd ..
	#if [ $TEST == "-DTEST=ON"]
	#	then
	#		./exec/test/SupervisorDaemon-test
	#fi
fi
